(ns clj-bytes.protocols
  (:refer-clojure :exclude [-empty -count -seq]))

(defprotocol BytesImpl
  "Protocol for byte array implementation."
  (-instance? [this b])
  (-class [this])
  (-make [this n])
  (-rand [this n])
  (-empty [this])
  (-empty? [this b])
  (-equal? [this b1 b2])
  (-count [this b])
  (-get [this b n])
  (-set! [this b n i])
  (-fill! [this b i])
  (-seq [this b])
  (-of-seq [this s])
  (-uget [this b n])
  (-uset! [this b n i])
  (-ufill! [this b i])
  (-useq [this b])
  (-of-useq [this b])
  (-sub [this b s e])
  (-concat [this bs])
  (-str [this b encoding])
  (-of-str [this s encoding])
  (-int [this b encoding])
  (-of-int [this i encoding]))
